
    $(function(){
        $('.one').mouseover(function(){
            $(this).stop();
            $(this).animate({'left':'0'},300);
        }).mouseout(function(){
            $(this).stop();
            $(this).animate({'left':'-90%'},300);
        });
        $('.two').mouseover(function(){
            $(this).stop();
            $(this).animate({'left':'0'},300);
        }).mouseout(function(){
            $(this).stop();
            $(this).animate({'left':'-80%'},300);
        })
        $('.three').mouseover(function(){
            $(this).stop();
            $(this).animate({'left':'0'},300);
        }).mouseout(function(){
            $(this).stop();
            $(this).animate({'left':'-70%'},300);
        })
        $('.four').mouseover(function(){
            $(this).stop();
            $(this).animate({'left':'0'},300);
        }).mouseout(function(){
            $(this).stop();
            $(this).animate({'left':'-60%'},300);
        })
        $('.five').mouseover(function(){
            $(this).stop();
            $(this).animate({'left':'0'},300);
        }).mouseout(function(){
            $(this).stop();
            $(this).animate({'left':'-60%'},300);
        })
        $('.six').mouseover(function(){
            $(this).stop();
            $(this).animate({'left':'0'},300);
        }).mouseout(function(){
            $(this).stop();
            $(this).animate({'left':'-70%'},300);
        })
        $('.seven').mouseover(function(){
            $(this).stop();
            $(this).animate({'left':'0'},300);
        }).mouseout(function(){
            $(this).stop();
            $(this).animate({'left':'-80%'},300);
        })
        $('.eight').mouseover(function(){
            $(this).stop();
            $(this).animate({'left':'0'},300);
        }).mouseout(function(){
            $(this).stop();
            $(this).animate({'left':'-90%'},300);
        })

    });
